{
    // NUEVO — creación completa
    slug: "logistica-expresa",
    name: "Logística Expresa",
    theme: { primaryColor: "#7C3AED", accentColor: "#A78BFA", secondaryColor: "#DDD6FE", titleSuffix: "Logística Expresa" },
    features: { accounting: false, maps: true, aiAssistant: false, equipmentManagement: true },
    orderTarget: 45,
    users: [
      { name: "Néstor Quiroga", username: "lo_admin", role: "admin", identification: "600000001" },
      { name: "Olga Pabón", username: "lo_sup", role: "supervisor", identification: "600000002" },
      { name: "Patricio Núñez", username: "lo_aux", role: "aux_admin", identification: "600000003" },
      { name: "Quintina Romero", username: "lo_dev", role: "developer", identification: "600000004" },
      { name: "Raúl Cabrales", username: "lo_tec1", role: "technician", identification: "600000005" },
      { name: "Silvia Medina", username: "lo_tec2", role: "technician", identification: "600000006" },
      { name: "Teodoro Aguirre", username: "lo_tec3", role: "technician", identification: "600000007" },
    ],
    clients: [
      { name: "Centro de Distribución Norte", address: "Autopista Norte km 16", contact: "Viviana Ruiz", identification: "930000001", email: "cdnorte@logexpress.co", lat: 4.7742, lng: -74.0367, neighborhood: "Usaquén", city: "Bogotá" },
      { name: "Bodega Regional Occidente", address: "Av. 68 # 75A-120", contact: "William Cárdenas", identification: "930000002", email: "bodegaocc@logexpress.co", lat: 4.6833, lng: -74.0718, neighborhood: "Engativá", city: "Bogotá" },
      { name: "Terminal de Carga Sur", address: "Carrera 30 # 105 - 50", contact: "Ximena Osorio", identification: "930000003", email: "tecargasur@logexpress.co", lat: 4.594, lng: -74.146, neighborhood: "Kennedy", city: "Bogotá" },
      { name: "Estación de Acopio Oriental", address: "Cra 7 # 116 - 30", contact: "Yolanda Serrano", identification: "930000004", email: "acopioor@logexpress.co", lat: 4.7186, lng: -74.0294, neighborhood: "Barrios Unidos", city: "Bogotá" },
      { name: "Cliente Mayorista Colombia SAS", address: "Calle 13 # 20 - 75", contact: "Zacarías Hoyos", identification: "930000005", email: "mayorista@logexpress.co", lat: 4.6029, lng: -74.0882, neighborhood: "Los Mártires", city: "Bogotá" },
    ],
    equipment: [
      { name: "Montacargas diésel 3T", brand: "Hyster", description: "Movimiento de carga pesada", serial_number: "LO-MD-001", voltage: "110V", maintenance_frequency: 3, last_maintenance_date: iso(-25) },
      { name: "Banda transportadora de paquetes", brand: "Intralox", description: "Línea de clasificación", serial_number: "LO-BP-002", voltage: "220V", maintenance_frequency: 6, last_maintenance_date: iso(-40) },
      { name: "Sistema de clasificación automática", brand: "Vanderlande", description: "Sorter de maletas", serial_number: "LO-SC-003", voltage: "330V", maintenance_frequency: 6, last_maintenance_date: iso(0) },
      { name: "Traspaleta eléctrica 1.8T", brand: "Jungheinrich", description: "Movimiento interno de pallets", serial_number: "LO-TE-004", voltage: "110V", maintenance_frequency: 6, last_maintenance_date: iso(-60) },
      { name: "Apilador eléctrico 2.5T", brand: "Lind", description: "Apilado de estibas", serial_number: "LO-AE-005", voltage: "110V", maintenance_frequency: 6, last_maintenance_date: iso(-15) },
      { name: "Grúa horquilla 4T", brand: "Toyota", description: "Carga de camiones", serial_number: "LO-GH-006", voltage: "110V", maintenance_frequency: 3, last_maintenance_date: iso(-50) },
      { name: "Motoconformadora CAT 140", brand: "Caterpillar", description: "Mantenimiento de patio", serial_number: "LO-MC-007", voltage: "110V", maintenance_frequency: 12, last_maintenance_date: iso(-180) },
      { name: "Compresor de tornillo 30HP", brand: "Sullair", description: "Aire comprimido de taller", serial_number: "LO-CT-008", voltage: "330V", maintenance_frequency: 6, last_maintenance_date: iso(-35) },
      { name: "Grupo electrógeno 500kVA", brand: "Cummins", description: "Respaldo energético", serial_number: "LO-GE-009", voltage: "330V", maintenance_frequency: 12, last_maintenance_date: iso(-100) },
      { name: "Báscula electrónica de plataforma", brand: "Avery", description: "Pesaje de mercancía", serial_number: "LO-BE-010", voltage: "110V", maintenance_frequency: 6, last_maintenance_date: iso(-5) },
    ],
    inventory: [
      { sku: "LO-A001", name: "Aceite de motor diésel (galón)", unit: "galón", quantity: 30, unit_cost: 38000, low_stock_threshold: 15 },
      { sku: "LO-A002", name: "Aceite hidráulico ISO 32", unit: "galón", quantity: 18, unit_cost: 42000, low_stock_threshold: 12 },
      { sku: "LO-G003", name: "Grasa para rodamientos (pote)", unit: "pote", quantity: 40, unit_cost: 16000, low_stock_threshold: 25 },
      { sku: "LO-F004", name: "Filtro de combustible diésel", unit: "unidad", quantity: 15, unit_cost: 27000, low_stock_threshold: 12 },
      { sku: "LO-F005", name: "Filtro de aire motor CAT", unit: "unidad", quantity: 6, unit_cost: 115000, low_stock_threshold: 8 },
      { sku: "LO-B006", name: "Batería montacargas 48V", unit: "unidad", quantity: 2, unit_cost: 3200000, low_stock_threshold: 3 },
      { sku: "LO-N007", name: "Neumático macizo 4T", unit: "unidad", quantity: 4, unit_cost: 480000, low_stock_threshold: 6 },
      { sku: "LO-EL008", name: "Contactor de potencia 3x80A", unit: "unidad", quantity: 12, unit_cost: 95000, low_stock_threshold: 10 },
      { sku: "LO-H009", name: "Refrigerante 50/50 (galón)", unit: "galón", quantity: 25, unit_cost: 22000, low_stock_threshold: 15 },
    ],
    services: [
      { category: "Correctivo", service_name: "Reparación de motor", descriptions: ["Sobrecalentamiento de motor, revisión de termostato.", "Fallo de arranque por inyectores."] },
      { category: "Correctivo", service_name: "Reparación hidráulica", descriptions: ["Caída de presión en montacargas, revisión de bomba.", "Sello de cilindro de elevación."] },
      { category: "Correctivo", service_name: "Reparación eléctrica", descriptions: ["Corto en sistema de clasificación.", "Fallo de sensor en banda transportadora."] },
      { category: "Correctivo", service_name: "Reparación mecánica", descriptions: ["Cambio de neumático macizo.", "Ajuste de frenos de montacargas."] },
      { category: "Correctivo", service_name: "Soporte en línea", descriptions: ["Atasco de paquetes en sorter, liberación.", "Reinicio y configuración de clasificador."] },
      { category: "Preventivo", service_name: "Mantenimiento preventivo", descriptions: ["Servicio programado de montacargas.", "Lubricación de banda transportadora."] },
      { category: "Preventivo", service_name: "Inspección de seguridad", descriptions: ["Verificación de paros de emergencia y barreras.", "Revisión de cableado y tierra."] },
      { category: "Preventivo", service_name: "Revisión de equipos de patio", descriptions: ["Chequeo de nivel de combustible y refrigerante.", "Inspección visual de fugas."] },
    ],
    tasks: [
      { title: "Calibración de báscula de plataforma", assigned: "lo_tec1", category: "Calibración", due: iso(1), important: true },
      { title: "Servicio técnico de grúa horquilla", assigned: "lo_tec2", category: "Mantenimiento", due: iso(2) },
      { title: "Inspección de grupo electrógeno", assigned: "lo_tec3", category: "Prevención", due: iso(4) },
      { title: "Pedido de batería de repuesto", assigned: "lo_aux", category: "Inventario", due: iso(5) },
      { title: "Revisión de sorter de maletas", assigned: "lo_tec1", category: "Sistemas", due: iso(7), important: true },
      { title: "Reemplazo de neumáticos macizos", assigned: "lo_tec2", category: "Mantenimiento", due: iso(10) },
    ],
    support: [
      { subject: "Error al exportar informe de trabajo", message: "La exportación de PDF del informe de órdenes falla cuando hay muchos datos. Revisar por favor.", status: "en_progreso" },
      { subject: "Alta de nuevo usuario en recepción", message: "Solicito se cree una cuenta de técnico para la sede de acopio con permiso de lectura.", status: "abierto" },
    ],
  },
  {
    // EXISTENTE — solo enriquecer data (reusa users ya enlazados)
    name: "Fábricas Andinas S.A.",
    orderTarget: 40,
    users: [],
    inventory: [
      { sku: "FA-A001", name: "Aceite hidráulico ISO 68 (barril)", unit: "barril", quantity: 10, unit_cost: 1850000, low_stock_threshold: 6 },
      { sku: "FA-A002", name: "Grasa para rodamientos (pote)", unit: "pote", quantity: 20, unit_cost: 18500, low_stock_threshold: 15 },
      { sku: "FA-F003", name: "Filtro de aceite GA75", unit: "unidad", quantity: 5, unit_cost: 175000, low_stock_threshold: 4 },
      { sku: "FA-M004", name: "Motor eléctrico 15HP", unit: "unidad", quantity: 2, unit_cost: 2800000, low_stock_threshold: 3 },
      { sku: "FA-R005", name: "Rodamiento SKF 6307", unit: "unidad", quantity: 30, unit_cost: 52000, low_stock_threshold: 20 },
      { sku: "FA-C006", name: "Soldadura MIG ER70S-6 (rollo)", unit: "rollo", quantity: 12, unit_cost: 145000, low_stock_threshold: 8 },
    ],
    services: [
      { category: "Preventivo", service_name: "Mantenimiento preventivo", descriptions: ["Cambio de aceite hidráulico y revisión de sellos.", "Limpieza y ajuste general de la máquina."] },
      { category: "Correctivo", service_name: "Reparación hidráulica", descriptions: ["Fuga de aceite en cilindro principal, cambio de sello.", "Presión hidráulica inestable, revisar válvula."] },
      { category: "Correctivo", service_name: "Reparación mecánica", descriptions: ["Ruido anormal en reductora, cambio de rodamiento.", "Desalineación de husillo."] },
      { category: "Correctivo", service_name: "Reparación eléctrica", descriptions: ["Contactor de arranque quemado, reemplazo.", "Fallos intermitentes en tablero de control."] },
    ],
    tasks: [
      { title: "Engrase semanal Prensa Hidráulica", assigned: "a_tec1", category: "Mantenimiento", due: iso(1), important: true },
      { title: "Inspección de seguridad Montacargas", assigned: "a_tec2", category: "Prevención", due: iso(2) },
      { title: "Preparar pedido de rodamientos", assigned: "a_aux", category: "Inventario", due: iso(4) },
      { title: "Prueba de estanqueidad compresor", assigned: "a_tec1", category: "Calidad", due: iso(6) },
      { title: "Actualizar plano de planta", assigned: "a_admin", category: "Documentación", due: iso(9) },
      { title: "Revisión de niveles de refrigerante", assigned: "a_tec2", category: "Mantenimiento", due: iso(11) },
    ],
  },
  {
    // EXISTENTE — solo enriquecer data
    name: "Hoteles Caribe LTDA",
    orderTarget: 40,
    users: [],
    inventory: [
      { sku: "HC-A001", name: "Refrigerante R410A (cilindro)", unit: "cilindro", quantity: 3, unit_cost: 450000, low_stock_threshold: 2 },
      { sku: "HC-A002", name: "Gas refrigerante R22 (cilindro)", unit: "cilindro", quantity: 2, unit_cost: 850000, low_stock_threshold: 1 },
      { sku: "HC-F003", name: "Filtro de aire chiller (set)", unit: "set", quantity: 5, unit_cost: 115000, low_stock_threshold: 6 },
      { sku: "HC-B004", name: "Bomba de sumidero 2HP", unit: "unidad", quantity: 1, unit_cost: 650000, low_stock_threshold: 2 },
      { sku: "HC-E005", name: "Contactor 3x32A", unit: "unidad", quantity: 10, unit_cost: 58000, low_stock_threshold: 8 },
      { sku: "HC-N006", name: "Neumático montacargas 2.5T", unit: "unidad", quantity: 2, unit_cost: 380000, low_stock_threshold: 4 },
    ],
    services: [
      { category: "Preventivo", service_name: "Climatización", descriptions: ["Limpieza y carga de refrigerante R410A.", "Revisión de presiones de chiller."] },
      { category: "Correctivo", service_name: "Hidráulica", descriptions: ["Revisión de capacitor y sello mecánico.", "Fuga en bomba de piscina."] },
      { category: "Correctivo", service_name: "Eléctrico", descriptions: ["Sobrecalentamiento en tablero de piscina.", "Fallo en arranque de planta eléctrica."] },
      { category: "Preventivo", service_name: "Mantenimiento preventivo", descriptions: ["Limpieza y lubricación de equipos.", "Revisión de niveles y filtros."] },
    ],
    tasks: [
      { title: "Chequeo trimestral planta CAT", assigned: "h_tec1", category: "Respaldo", due: iso(3) },
      { title: "Revisión de filtros de chiller", assigned: "h_tec1", category: "Climatización", due: iso(1), important: true },
      { title: "Inspección de bomba de piscina", assigned: "h_tec1", category: "Piscina", due: iso(5) },
      { title: "Pedido de neumáticos para montacargas", assigned: "h_aux", category: "Inventario", due: iso(8) },
    ],
  },
  {
    // EXISTENTE — solo enriquecer data
    name: "Cementos Pacífico",
    orderTarget: 40,
    users: [],
    inventory: [
      { sku: "CP-B001", name: "Blindaje de molino (set)", unit: "set", quantity: 2, unit_cost: 12500000, low_stock_threshold: 3 },
      { sku: "CP-R002", name: "Rodillo de chancadora (repuesto)", unit: "unidad", quantity: 1, unit_cost: 3800000, low_stock_threshold: 2 },
      { sku: "CP-A003", name: "Aceite de molino ISO 150", unit: "barril", quantity: 8, unit_cost: 2100000, low_stock_threshold: 5 },
      { sku: "CP-RE004", name: "Refractario de horno (kg)", unit: "kg", quantity: 1500, unit_cost: 8500, low_stock_threshold: 1000 },
      { sku: "CP-F005", name: "Filtro de mangas (bolsa)", unit: "bolsa", quantity: 60, unit_cost: 32000, low_stock_threshold: 80 },
      { sku: "CP-M006", name: "Motorreductor 3/1 (11kW)", unit: "unidad", quantity: 2, unit_cost: 5400000, low_stock_threshold: 2 },
    ],
    services: [
      { category: "Preventivo", service_name: "Molienda", descriptions: ["Reemplazo de blindajes del molino.", "Revisión de carga de bolas."] },
      { category: "Correctivo", service_name: "Trituración", descriptions: ["Sobrecalentamiento de cojinetes.", "Revisión de alineación de chancadora."] },
      { category: "Correctivo", service_name: "Clinkerización", descriptions: ["Revisión de refractario del horno.", "Ajuste de quemadores."] },
      { category: "Preventivo", service_name: "Inspección de seguridad", descriptions: ["Verificación de guardas.", "Control de polvo en planta."] },
    ],
    tasks: [
      { title: "Inspección de refractario Horno", assigned: "c_tec1", category: "Alta temperatura", due: iso(3), important: true },
      { title: "Cambio de filtros de mangas", assigned: "c_tec1", category: "Mantenimiento", due: iso(2) },
      { title: "Revisión de carga de bolas molino", assigned: "c_tec1", category: "Molienda", due: iso(5) },
      { title: "Pedido de blindajes de molino", assigned: "c_aux", category: "Inventario", due: iso(7) },
    ],
  },
];